import type { Category, TableSchema } from "./schema";

export const categories: Category[] = [
    {
        id: "ventas",
        nombre: "Ventas",
        description: "Gestión de operaciones comerciales",
    },
    {
        id: "operaciones",
        nombre: "Operaciones",
        description: "Procesos operativos",
    },
    {
        id: "inventario",
        nombre: "Inventario",
        description: "Control de stock y productos",
    },
    { id: "rrhh", nombre: "RRHH", description: "Recursos humanos" },
    {
        id: "administracion",
        nombre: "Administración",
        description: "Gestión administrativa",
    },
    { id: "calidad", nombre: "Calidad", description: "Control de calidad" },
];

export const mockTables: TableSchema[] = [
    {
        id: "clientes",
        name: "clientes",
        displayName: "Clientes",
        description: "Registro de clientes y datos de contacto",
        category: "ventas",
        columns: [
            {
                name: "nombre_empresa",
                displayName: "Nombre de empresa",
                type: "varchar",
                required: true,
                maxLength: 200,
                placeholder: "Ej: Acme Corp",
            },
            {
                name: "contacto_principal",
                displayName: "Contacto principal",
                type: "varchar",
                required: true,
                maxLength: 100,
            },
            {
                name: "email",
                displayName: "Email",
                type: "varchar",
                required: true,
                maxLength: 150,
                placeholder: "email@ejemplo.com",
            },
            {
                name: "telefono",
                displayName: "Teléfono",
                type: "varchar",
                nullable: true,
                maxLength: 20,
            },
            {
                name: "pais",
                displayName: "País",
                type: "enum",
                required: true,
                enumValues: [
                    "España",
                    "México",
                    "Argentina",
                    "Colombia",
                    "Chile",
                    "Perú",
                ],
            },
            {
                name: "activo",
                displayName: "Cliente activo",
                type: "boolean",
                defaultValue: true,
            },
            {
                name: "fecha_registro",
                displayName: "Fecha de registro",
                type: "date",
                required: true,
            },
        ],
    },
    {
        id: "pedidos",
        name: "pedidos",
        displayName: "Pedidos",
        description: "Gestión de pedidos de clientes",
        category: "ventas",
        columns: [
            {
                name: "numero_pedido",
                displayName: "Número de pedido",
                type: "varchar",
                required: true,
                maxLength: 50,
                placeholder: "PED-2026-001",
            },
            {
                name: "cliente_id",
                displayName: "Cliente",
                type: "foreign_key",
                required: true,
                foreignKeyOptions: [
                    { value: "1", label: "Acme Corp" },
                    { value: "2", label: "TechSolutions SA" },
                    { value: "3", label: "Global Imports Ltd" },
                ],
            },
            {
                name: "fecha_pedido",
                displayName: "Fecha del pedido",
                type: "datetime",
                required: true,
            },
            {
                name: "monto_total",
                displayName: "Monto total",
                type: "decimal",
                required: true,
                placeholder: "0.00",
            },
            {
                name: "estado",
                displayName: "Estado",
                type: "enum",
                required: true,
                enumValues: [
                    "Pendiente",
                    "En proceso",
                    "Enviado",
                    "Entregado",
                    "Cancelado",
                ],
                defaultValue: "Pendiente",
            },
            {
                name: "notas",
                displayName: "Notas",
                type: "text",
                nullable: true,
                placeholder: "Observaciones adicionales...",
            },
        ],
    },
    {
        id: "productos",
        name: "productos",
        displayName: "Productos",
        description: "Catálogo de productos",
        category: "inventario",
        columns: [
            {
                name: "sku",
                displayName: "SKU",
                type: "varchar",
                required: true,
                maxLength: 50,
                placeholder: "PROD-001",
            },
            {
                name: "nombre",
                displayName: "Nombre del producto",
                type: "varchar",
                required: true,
                maxLength: 200,
            },
            {
                name: "descripcion",
                displayName: "Descripción",
                type: "text",
                nullable: true,
            },
            {
                name: "precio_unitario",
                displayName: "Precio unitario",
                type: "decimal",
                required: true,
                placeholder: "0.00",
            },
            {
                name: "stock_actual",
                displayName: "Stock actual",
                type: "integer",
                required: true,
                defaultValue: 0,
            },
            {
                name: "stock_minimo",
                displayName: "Stock mínimo",
                type: "integer",
                required: true,
                defaultValue: 10,
            },
            {
                name: "categoria",
                displayName: "Categoría",
                type: "enum",
                required: true,
                enumValues: [
                    "Electrónica",
                    "Ropa",
                    "Alimentación",
                    "Hogar",
                    "Deportes",
                    "Otros",
                ],
            },
            {
                name: "activo",
                displayName: "Producto activo",
                type: "boolean",
                defaultValue: true,
            },
        ],
    },
    {
        id: "movimientos_inventario",
        name: "movimientos_inventario",
        displayName: "Movimientos de Inventario",
        description: "Registro de entradas y salidas de stock",
        category: "inventario",
        columns: [
            {
                name: "producto_id",
                displayName: "Producto",
                type: "foreign_key",
                required: true,
                foreignKeyOptions: [
                    { value: "1", label: "Laptop HP ProBook" },
                    { value: "2", label: "Mouse Logitech MX" },
                    { value: "3", label: "Teclado mecánico" },
                ],
            },
            {
                name: "tipo_movimiento",
                displayName: "Tipo de movimiento",
                type: "enum",
                required: true,
                enumValues: ["Entrada", "Salida", "Ajuste", "Devolución"],
            },
            {
                name: "cantidad",
                displayName: "Cantidad",
                type: "integer",
                required: true,
            },
            {
                name: "fecha_movimiento",
                displayName: "Fecha del movimiento",
                type: "datetime",
                required: true,
            },
            {
                name: "motivo",
                displayName: "Motivo",
                type: "text",
                nullable: true,
            },
        ],
    },
    {
        id: "empleados",
        name: "empleados",
        displayName: "Empleados",
        description: "Información de personal",
        category: "rrhh",
        columns: [
            {
                name: "nombre_completo",
                displayName: "Nombre completo",
                type: "varchar",
                required: true,
                maxLength: 150,
            },
            {
                name: "email_corporativo",
                displayName: "Email corporativo",
                type: "varchar",
                required: true,
                maxLength: 150,
                placeholder: "nombre@empresa.com",
            },
            {
                name: "departamento",
                displayName: "Departamento",
                type: "enum",
                required: true,
                enumValues: [
                    "Ventas",
                    "Operaciones",
                    "RRHH",
                    "IT",
                    "Finanzas",
                    "Marketing",
                ],
            },
            {
                name: "puesto",
                displayName: "Puesto",
                type: "varchar",
                required: true,
                maxLength: 100,
            },
            {
                name: "fecha_ingreso",
                displayName: "Fecha de ingreso",
                type: "date",
                required: true,
            },
            {
                name: "salario_mensual",
                displayName: "Salario mensual",
                type: "decimal",
                required: true,
            },
            {
                name: "activo",
                displayName: "Empleado activo",
                type: "boolean",
                defaultValue: true,
            },
        ],
    },
    {
        id: "ordenes_trabajo",
        name: "ordenes_trabajo",
        displayName: "Órdenes de Trabajo",
        description: "Gestión de tareas operativas",
        category: "operaciones",
        columns: [
            {
                name: "numero_orden",
                displayName: "Número de orden",
                type: "varchar",
                required: true,
                maxLength: 50,
                placeholder: "OT-2026-001",
            },
            {
                name: "titulo",
                displayName: "Título",
                type: "varchar",
                required: true,
                maxLength: 200,
            },
            {
                name: "descripcion",
                displayName: "Descripción",
                type: "text",
                required: true,
            },
            {
                name: "responsable_id",
                displayName: "Responsable",
                type: "foreign_key",
                required: true,
                foreignKeyOptions: [
                    { value: "1", label: "Juan Pérez" },
                    { value: "2", label: "María García" },
                    { value: "3", label: "Carlos López" },
                ],
            },
            {
                name: "prioridad",
                displayName: "Prioridad",
                type: "enum",
                required: true,
                enumValues: ["Baja", "Media", "Alta", "Urgente"],
                defaultValue: "Media",
            },
            {
                name: "fecha_inicio",
                displayName: "Fecha de inicio",
                type: "datetime",
                required: true,
            },
            {
                name: "fecha_limite",
                displayName: "Fecha límite",
                type: "datetime",
                nullable: true,
            },
            {
                name: "completada",
                displayName: "Completada",
                type: "boolean",
                defaultValue: false,
            },
        ],
    },
    {
        id: "facturas",
        name: "facturas",
        displayName: "Facturas",
        description: "Registro de facturación",
        category: "administracion",
        columns: [
            {
                name: "numero_factura",
                displayName: "Número de factura",
                type: "varchar",
                required: true,
                maxLength: 50,
                placeholder: "FAC-2026-001",
            },
            {
                name: "cliente_id",
                displayName: "Cliente",
                type: "foreign_key",
                required: true,
                foreignKeyOptions: [
                    { value: "1", label: "Acme Corp" },
                    { value: "2", label: "TechSolutions SA" },
                    { value: "3", label: "Global Imports Ltd" },
                ],
            },
            {
                name: "fecha_emision",
                displayName: "Fecha de emisión",
                type: "date",
                required: true,
            },
            {
                name: "fecha_vencimiento",
                displayName: "Fecha de vencimiento",
                type: "date",
                required: true,
            },
            {
                name: "monto_subtotal",
                displayName: "Subtotal",
                type: "decimal",
                required: true,
            },
            {
                name: "impuestos",
                displayName: "Impuestos",
                type: "decimal",
                required: true,
            },
            {
                name: "monto_total",
                displayName: "Total",
                type: "decimal",
                required: true,
            },
            {
                name: "pagada",
                displayName: "Pagada",
                type: "boolean",
                defaultValue: false,
            },
        ],
    },
    {
        id: "inspecciones_calidad",
        name: "inspecciones_calidad",
        displayName: "Inspecciones de Calidad",
        description: "Control y auditoría de calidad",
        category: "calidad",
        columns: [
            {
                name: "codigo_inspeccion",
                displayName: "Código de inspección",
                type: "varchar",
                required: true,
                maxLength: 50,
                placeholder: "INS-2026-001",
            },
            {
                name: "producto_id",
                displayName: "Producto inspeccionado",
                type: "foreign_key",
                required: true,
                foreignKeyOptions: [
                    { value: "1", label: "Laptop HP ProBook" },
                    { value: "2", label: "Mouse Logitech MX" },
                    { value: "3", label: "Teclado mecánico" },
                ],
            },
            {
                name: "inspector_id",
                displayName: "Inspector",
                type: "foreign_key",
                required: true,
                foreignKeyOptions: [
                    { value: "1", label: "Ana Martínez" },
                    { value: "2", label: "Roberto Silva" },
                ],
            },
            {
                name: "fecha_inspeccion",
                displayName: "Fecha de inspección",
                type: "datetime",
                required: true,
            },
            {
                name: "resultado",
                displayName: "Resultado",
                type: "enum",
                required: true,
                enumValues: ["Aprobado", "Rechazado", "Requiere revisión"],
            },
            {
                name: "observaciones",
                displayName: "Observaciones",
                type: "text",
                nullable: true,
            },
            {
                name: "puntuacion",
                displayName: "Puntuación (0-100)",
                type: "integer",
                nullable: true,
            },
        ],
    },
];

export const getTablesByCategory = (categoryId: string): TableSchema[] => {
    return mockTables.filter((table) => table.category === categoryId);
};

export const getTableById = (tableId: string): TableSchema | undefined => {
    return mockTables.find((table) => table.id === tableId);
};

export const getCategoryById = (categoryId: string): Category | undefined => {
    return categories.find((cat) => cat.id === categoryId);
};
