name: Deploy Frontend (Azure Static Web Apps)

on:
  push:
    branches:
      - main
    paths:
      - 'applications/web-app/**'
      - '.github/workflows/deploy-frontend.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build & Deploy to Azure
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Install OIDC client
        run: npm install @actions/core@1.6.0 @actions/http-client

      - name: Get OIDC token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coreLib = require('@actions/core')
            return await coreLib.getIDToken()
          result-encoding: string

      - name: Build & Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          VITE_API_SERVER: ${{ secrets.VITE_API_SERVER }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_WATER_03112DC0F }}
          action: "upload"
          app_location: "./applications/web-app"
          api_location: ""
          output_location: "dist"
          github_id_token: ${{ steps.idtoken.outputs.result }}

  close_pull_request:
    name: Close PR Preview
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
